### ISSUE TITLE
可以加一个这样的功能，我感觉有这个功能后，完成度就非常高了

### ISSUE THREAD

**Issue by zlyhsjd** [mkch/DeMic#1]
以前是对所有设备全部静音了，有些不好，这个新加一个选项后，就可以针对性只对（默认麦克风设备）或者（全部）或者（选定的麦克风设备）或者（预设麦克风组）产生作用。

如果up能更新一下，将不胜感激，已经给up《【二手码农】一键静音麦克风》这两个视频都三连了，要是软件更新了还会给up新视频三连，嘿嘿，
![image](https://user-images.githubusercontent.com/84318632/204259311-297409ac-8ba0-43b0-ad42-2c492cf164bc.png)

**Comment by mkch** [comment]
做了一部分。参看 https://github.com/mkch/DeMic/releases/tag/v1.0

**Comment by zlyhsjd** [comment]
> 做了一部分。参看 https://github.com/mkch/DeMic/releases/tag/v1.0

太棒了，没有任何问题，这点就够用了，够用了
