### ISSUE TITLE
游戏中全局快捷键失效

### ISSUE THREAD

**Issue by kanoshiou** [mkch/DeMic#2]
在英雄联盟游戏中所有全局快捷键会失效，这个应该是腾讯搞的鬼。
试了其他应用的全局快捷键也会失效，不知道是否可以绕过或者提优先级之类的操作？

**Comment by zlyhsjd** [comment]
用管理员权限运行DeMic还会出现这种情况吗？或者换别的快捷键试试？

**Comment by kanoshiou** [comment]
> 用管理员权限运行DeMic还会出现这种情况吗？或者换别的快捷键试试？

都试过了不行

**Comment by mkch** [comment]
我认为，最好不要挑战游戏的反作弊系统。目前先关闭，如果有更好的解决方案可再次打开此 issue。

**Comment by mkch** [comment]
试一下最新 [v1.3.2](https://github.com/mkch/DeMic/releases/tag/v1.3.2)。
启用 `Web 远程控制` 后，在手机上控制麦克风的开关。
