### ISSUE TITLE
作用到全部麦克风出现BUG（如图）

### ISSUE THREAD

**Issue by zlyhsjd** [mkch/DeMic#3]
![image](https://github.com/mkch/DeMic/assets/84318632/d36cf11c-5128-42ef-88dc-d068698b47e8)

鼠标一移动到[作用到全部麦克风]上就会报错
好像是使用绝对路径出现问题了，路径是作者电脑的onedrive地址

**Comment by zlyhsjd** [comment]
版本是最新的[v1.1.1]版本

**Comment by mkch** [comment]
你好，请问你的电脑总共有多少个麦克风？

**Comment by zlyhsjd** [comment]
有3个

**Comment by mkch** [comment]
你好，请下载这个 release 里的 Profile.plugin，替换到 plugin 目录试试。
https://github.com/mkch/DeMic/releases/tag/v1.1.2-aplpa
